import {
    helpCommand,
    clearCommand,
    exitCommand,
    levelCommand,
    decodeCommand,
    analyzeCommand,
    chatCommand,
    whoamiCommand,
    loganalyzerCommand,
    timelineCommand,
    traceCommand,
    lsCommand,
    cdCommand,
    catCommand,
    unlockCommand,
    hintCommand,
    saveCommand,
    loadCommand,
    deleteSaveCommand
} from "./basic";

export const commands = [
    helpCommand,
    lsCommand,
    cdCommand,
    catCommand,
    clearCommand,
    decodeCommand,
    unlockCommand,
    saveCommand,
    loadCommand,
    deleteSaveCommand,
    levelCommand,
    exitCommand,
    hintCommand,
    analyzeCommand,
    chatCommand,
    whoamiCommand,
    loganalyzerCommand,
    timelineCommand,
    traceCommand
]; 